"""Add timelines table and thinker timeline relationship

Revision ID: b8675b43aadb
Revises: e1514bd4bed2
Create Date: 2025-11-20 13:36:15.238643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8675b43aadb'
down_revision: Union[str, None] = 'e1514bd4bed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('thinkers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeline_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_thinkers_timeline_id', 'timelines', ['timeline_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinkers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_thinkers_timeline_id', type_='foreignkey')
        batch_op.drop_column('timeline_id')

    op.drop_table('timelines')
    # ### end Alembic commands ###
